version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openfga-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - openfga-network
    depends_on:
      - db
      - openfga
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=openfga_laravel
      - DB_USERNAME=openfga
      - DB_PASSWORD=secret
      - OPENFGA_URL=http://openfga:8080
      - OPENFGA_STORE_ID=${OPENFGA_STORE_ID}
      - OPENFGA_MODEL_ID=${OPENFGA_MODEL_ID}

  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: openfga-laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - openfga-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:9.5
    container_name: openfga-laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: openfga_laravel
      MYSQL_USER: openfga
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - openfga-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # OpenFGA Authorization Server
  openfga:
    image: openfga/openfga:latest
    container_name: openfga-server
    restart: unless-stopped
    command: run --playground-enabled
    ports:
      - "8080:8080" # API
      - "8081:8081" # gRPC
      - "3000:3000" # Playground
    networks:
      - openfga-network
    environment:
      - OPENFGA_DATASTORE_ENGINE=memory
      - OPENFGA_PLAYGROUND_ENABLED=true
      - OPENFGA_LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache (optional but recommended)
  redis:
    image: redis:alpine
    container_name: openfga-laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - openfga-network
    volumes:
      - redis-data:/data

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: openfga-laravel-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - openfga-network

networks:
  openfga-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local