version: 2
updates:
  # Maintain dependencies for PHP packages (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: widen
    labels:
      - "dependency"
      - "php"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "evansims"
    groups:
      # Group all production dependencies
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # Group all development dependencies
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Group major version updates separately
      major-updates:
        applies-to: version-updates
        update-types:
          - "major"
    
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependency"
      - "github_actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - "*"
