name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-integration-tests

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build test image
      run: |
        echo "Building test image with latest code..."
        docker buildx build \
          --cache-from type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache \
          --cache-to type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max \
          --tag evansims/openfga-laravel-integration-tests:latest \
          --file Dockerfile.integration \
          --load \
          .
        
        # Show image info
        echo "Built test image:"
        docker images evansims/openfga-laravel-integration-tests:latest --format "Repository: {{.Repository}} Size: {{.Size}}"

    - name: Run integration tests
      run: |
        # Use the regular compose file with the freshly built image
        docker compose -f docker-compose.integration.yml up -d openfga otel-collector
        sleep 10
        docker compose -f docker-compose.integration.yml run --rm test

    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose.integration.yml down -v
        docker ps -a --filter label=com.openfga.test=integration -q | xargs -r docker rm -f || true