name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-integration-tests

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull test image
      run: |
        echo "Pulling pre-built test image..."
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
        # Tag it for local use
        docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest evansims/openfga-laravel-integration-tests:latest
        
        # Show image info
        echo "Using test image:"
        docker images evansims/openfga-laravel-integration-tests:latest --format "Repository: {{.Repository}} Size: {{.Size}}"

    - name: Run integration tests
      run: |
        # Use the CI-specific compose file that expects pre-built images
        docker compose -f docker-compose.integration.ci.yml up -d openfga otel-collector
        sleep 10
        docker compose -f docker-compose.integration.ci.yml run --rm test

    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose.integration.ci.yml down -v
        docker ps -a --filter label=com.openfga.test=integration -q | xargs -r docker rm -f || true